apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: go-pod-server
  labels:
    app: go-pod-server
spec:
  replicas: 3
  serviceName: go-pod-headless-service
  selector:
    matchLabels:
      app: go-pod-server
  template:
    metadata:
      labels:
        app: go-pod-server
    spec:
      containers:
      - name: go-server
        image: go-pod-server:a19
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PORT
          value: "8080"
        - name: IPS
          valueFrom: 
            fieldRef:
              fieldPath: status.podIPs
        - name: REPLICAS
          value: "3"

---
apiVersion: v1
kind: Service
metadata:
  name: go-pod-server-service
spec:
  selector:
    app: go-pod-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: go-pod-headless-service
spec:
  selector:
    app: go-pod-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  clusterIP: None